/**
 * Homepage editorial copy (FR/EN).
 * Kept separate from the global translations file so the homepage art direction
 * can evolve without touching shared navigation / form strings.
 */

export type HomeCopy = typeof homeCopy.fr;

export const homeCopy = {
  fr: {
    hero: {
      eyebrow: "Programme communautaire RêvPÈRE · Montréal",
      titleA: "Reprendre sa place.",
      titleB: "Retrouver son autonomie.",
      subtitle:
        "RêvPÈRE accompagne les pères vers l'emploi et l'autonomie numérique grâce à des outils concrets : informatique, Web, télétravail et intelligence artificielle.",
      human:
        "Aider un père à se remettre debout, c'est aussi aider ses enfants à avancer.",
      ctaPrimary: "Commencer mon parcours",
      ctaSecondary: "Découvrir RêvPÈRE",
      ctaQuiet: "J'ai besoin d'une ressource",
      imageAlt:
        "Un père accompagné par une intervenante devant un ordinateur portable dans un centre communautaire",
    },
    signage: ["Emploi", "Numérique", "Web", "Télétravail", "IA", "Autonomie"],
    shift: {
      label: "Constat",
      titleA: "Le monde du travail",
      titleB: "a changé.",
      lead: "Chercher un emploi demande maintenant beaucoup plus que de remettre un CV.",
      items: [
        "Candidature en ligne",
        "PDF",
        "Courriel",
        "Teams",
        "Zoom",
        "LinkedIn",
        "Formulaires numériques",
        "Services gouvernementaux en ligne",
        "Intelligence artificielle",
      ],
      close: "RêvPÈRE veut aider les pères à franchir cette nouvelle barrière.",
      imageAlt: "Atelier communautaire où un père écrit son curriculum vitae",
    },
    pillarsIntro: {
      label: "Les cinq piliers RêvPÈRE",
      title: "Un parcours, cinq apprentissages.",
    },
    pillars: [
      {
        n: "01",
        key: "emploi",
        nav: "Emploi",
        title: "Retrouver le chemin du travail.",
        lead: "Reprendre confiance devant une offre d'emploi, une entrevue, un formulaire.",
        items: [
          "CV",
          "Lettre de présentation",
          "Recherche d'emploi",
          "Entrevue",
          "Retour au travail",
          "Changement de domaine",
          "Formation",
          "Projet professionnel",
        ],
        cta: "Découvrir RêvPÈRE Emploi",
        imageAlt: "Un homme rédige son curriculum vitae dans un centre d'emploi",
      },
      {
        n: "02",
        key: "numerique",
        nav: "Numérique",
        title: "Être autonome devant un ordinateur.",
        lead: "Les gestes de base, appris sans jugement, au rythme de chacun.",
        items: [
          "Courriel",
          "Documents",
          "PDF",
          "Word",
          "Excel",
          "Drive",
          "OneDrive",
          "Formulaires",
          "Cybersécurité",
        ],
        cta: "Découvrir RêvPÈRE Numérique",
        imageAlt: "Mains d'un participant sur un clavier lors d'un atelier informatique",
      },
      {
        n: "03",
        key: "web",
        nav: "Web",
        title: "Comprendre le Web plutôt que simplement le subir.",
        lead: "Naviguer, chercher, vérifier, se présenter — sans se sentir dépassé.",
        items: [
          "Navigateur",
          "Recherche",
          "LinkedIn",
          "Portfolio",
          "Formation",
          "Services en ligne",
        ],
        cta: "Découvrir RêvPÈRE Web",
        imageAlt: "Deux hommes regardent ensemble un navigateur Web sur un portable",
      },
      {
        n: "04",
        key: "distance",
        nav: "Télétravail",
        title: "Être prêt pour le travail d'aujourd'hui.",
        lead: "Une entrevue en visioconférence ne devrait jamais être un obstacle.",
        items: [
          "Teams",
          "Zoom",
          "Meet",
          "Outlook",
          "Calendrier",
          "Partage d'écran",
          "Documents collaboratifs",
          "Organisation",
        ],
        cta: "Découvrir RêvPÈRE Télétravail",
        imageAlt: "Un père en visioconférence depuis sa cuisine",
      },
      {
        n: "05",
        key: "ia",
        nav: "IA",
        title: "Faire de l'IA un outil d'autonomie.",
        lead: "Pas une mode. Un outil pour régler des problèmes concrets.",
        items: [
          "J'ai une entrevue demain.",
          "Je dois améliorer mon CV.",
          "Je ne comprends pas cette lettre.",
          "Je dois envoyer un courriel professionnel.",
          "Je veux apprendre quelque chose de nouveau.",
        ],
        cta: "Découvrir RêvPÈRE IA",
        imageAlt: "Un homme concentré devant un ordinateur portable",
      },
    ],
    method: {
      label: "Notre méthode",
      chapters: [
        {
          n: "01",
          title: "Nous enseignons",
          items: ["Emploi", "Ordinateur", "Web", "Télétravail", "IA"],
          body: "",
        },
        {
          n: "02",
          title: "Nous accompagnons",
          items: [],
          body: "Comprendre la situation. Identifier les obstacles. Préparer les prochaines démarches.",
        },
        {
          n: "03",
          title: "Nous connectons",
          items: [],
          body: "Quand le besoin dépasse notre spécialité, nous aidons le père à trouver le bon organisme.",
        },
      ],
    },
    resources: {
      titleA: "J'ai besoin d'aide.",
      titleB: "Où dois-je aller?",
      placeholder: "Décrivez ce dont vous avez besoin…",
      cta: "Trouver une ressource",
      examples: [
        "Séparation",
        "DPJ",
        "Logement",
        "Santé mentale",
        "Juridique",
        "Immigration",
        "Dépendances",
      ],
      note: "Le bottin RêvPÈRE oriente vers les organismes du Grand Montréal. Nous ne remplaçons pas ces services : nous aidons à y accéder.",
    },
    community: {
      label: "Communauté",
      title: "Être père, c'est aussi créer des moments qui comptent.",
      body: "Cuisine, parc, sport, informatique, événements familiaux : des occasions simples de renouer avec ses enfants et de sortir de l'isolement.",
      cta: "Voir la vie communautaire",
      alts: [
        "Un père et son enfant cuisinent ensemble",
        "Un père et son enfant dans un parc de Montréal",
        "Atelier communautaire informatique",
      ],
    },
    org: {
      label: "Organisation",
      title: "REVERS CANADA",
      body: "RêvPÈRE constitue notre programme communautaire destiné aux pères. REVERS CANADA développe également d'autres volets répondant à des besoins essentiels.",
      streams: {
        housingLabel: "Programme REVERS CANADA",
        housingTitle: "Créer aussi de la stabilité.",
        housingBody:
          "Le logement demeure la première condition d'une reprise durable. Nous travaillons à développer ce volet avec des partenaires du milieu.",
        housingCta: "Découvrir le volet habitation",
        foodLabel: "Programme REVERS CANADA",
        foodTitle: "Un soutien concret lorsque la famille en a besoin.",
        foodBody:
          "Sécurité alimentaire, dépannage et redistribution : un appui direct, sans démarches inutiles.",
        foodCta: "Découvrir l'aide alimentaire",
        intlLabel: "Mission REVERS CANADA",
        intlTitle: "Notre engagement peut aussi traverser les frontières.",
        intlBody:
          "Dons matériels : médicaments, vêtements et fournitures destinés aux communautés et aux animaux.",
        intlCta: "Découvrir le volet international",
      },
    },
    partners: {
      label: "Partenaires",
      title: "Les problèmes complexes se règlent en réseau.",
      body: "Nous ne cherchons pas à remplacer les organismes existants. Nous voulons être le point d'entrée qui mène au bon service, au bon moment.",
      categories: [
        "Organismes",
        "Entreprises",
        "Municipalités",
        "Fondations",
        "Formateurs",
        "Employeurs",
      ],
      cta: "Construire un partenariat",
    },
    final: {
      title: "Chaque parcours commence par une première démarche.",
      body: "Que vous cherchiez du travail, que vous vouliez devenir plus autonome avec le numérique ou que vous ne sachiez simplement pas par où commencer, RêvPÈRE peut vous aider à identifier la prochaine étape.",
      ctaPrimary: "Commencer mon parcours",
      ctaSecondary: "Nous contacter",
    },
  },

  en: {
    hero: {
      eyebrow: "RêvPÈRE community program · Montréal",
      titleA: "Take your place back.",
      titleB: "Regain your independence.",
      subtitle:
        "RêvPÈRE supports fathers toward employment and digital independence with concrete tools: computers, the Web, remote work and artificial intelligence.",
      human:
        "Helping a father get back on his feet also helps his children move forward.",
      ctaPrimary: "Start my journey",
      ctaSecondary: "Discover RêvPÈRE",
      ctaQuiet: "I need a resource",
      imageAlt:
        "A father working with a community worker at a laptop in a community centre",
    },
    signage: ["Employment", "Digital", "Web", "Remote work", "AI", "Independence"],
    shift: {
      label: "The reality",
      titleA: "The world of work",
      titleB: "has changed.",
      lead: "Looking for a job now takes far more than handing in a résumé.",
      items: [
        "Online applications",
        "PDF",
        "Email",
        "Teams",
        "Zoom",
        "LinkedIn",
        "Digital forms",
        "Online government services",
        "Artificial intelligence",
      ],
      close: "RêvPÈRE helps fathers cross this new barrier.",
      imageAlt: "Community workshop where a father writes his résumé",
    },
    pillarsIntro: {
      label: "The five RêvPÈRE pillars",
      title: "One journey, five skills.",
    },
    pillars: [
      {
        n: "01",
        key: "emploi",
        nav: "Employment",
        title: "Finding the way back to work.",
        lead: "Regaining confidence in front of a job posting, an interview, a form.",
        items: [
          "Résumé",
          "Cover letter",
          "Job search",
          "Interview",
          "Return to work",
          "Career change",
          "Training",
          "Professional plan",
        ],
        cta: "Discover RêvPÈRE Employment",
        imageAlt: "A man writing his résumé in an employment centre",
      },
      {
        n: "02",
        key: "numerique",
        nav: "Digital",
        title: "Being independent at a computer.",
        lead: "The basics, taught without judgement, at each person's pace.",
        items: [
          "Email",
          "Documents",
          "PDF",
          "Word",
          "Excel",
          "Drive",
          "OneDrive",
          "Forms",
          "Cybersecurity",
        ],
        cta: "Discover RêvPÈRE Digital",
        imageAlt: "A participant's hands on a keyboard during a computer workshop",
      },
      {
        n: "03",
        key: "web",
        nav: "Web",
        title: "Understanding the Web instead of just enduring it.",
        lead: "Browsing, searching, verifying, presenting yourself — without feeling lost.",
        items: [
          "Browser",
          "Search",
          "LinkedIn",
          "Portfolio",
          "Training",
          "Online services",
        ],
        cta: "Discover RêvPÈRE Web",
        imageAlt: "Two men looking at a web browser together on a laptop",
      },
      {
        n: "04",
        key: "distance",
        nav: "Remote work",
        title: "Being ready for today's workplace.",
        lead: "A video interview should never be an obstacle.",
        items: [
          "Teams",
          "Zoom",
          "Meet",
          "Outlook",
          "Calendar",
          "Screen sharing",
          "Collaborative documents",
          "Organisation",
        ],
        cta: "Discover RêvPÈRE Remote work",
        imageAlt: "A father in a video meeting from his kitchen",
      },
      {
        n: "05",
        key: "ia",
        nav: "AI",
        title: "Turning AI into a tool for independence.",
        lead: "Not a trend. A tool for solving real problems.",
        items: [
          "I have an interview tomorrow.",
          "I need to improve my résumé.",
          "I don't understand this letter.",
          "I have to send a professional email.",
          "I want to learn something new.",
        ],
        cta: "Discover RêvPÈRE AI",
        imageAlt: "A man focused on a laptop",
      },
    ],
    method: {
      label: "Our method",
      chapters: [
        {
          n: "01",
          title: "We teach",
          items: ["Employment", "Computers", "Web", "Remote work", "AI"],
          body: "",
        },
        {
          n: "02",
          title: "We support",
          items: [],
          body: "Understand the situation. Identify the obstacles. Prepare the next steps.",
        },
        {
          n: "03",
          title: "We connect",
          items: [],
          body: "When a need goes beyond our expertise, we help the father find the right organisation.",
        },
      ],
    },
    resources: {
      titleA: "I need help.",
      titleB: "Where should I go?",
      placeholder: "Describe what you need…",
      cta: "Find a resource",
      examples: [
        "Separation",
        "Youth protection",
        "Housing",
        "Mental health",
        "Legal",
        "Immigration",
        "Addiction",
      ],
      note: "The RêvPÈRE directory points to organisations across Greater Montréal. We do not replace those services: we help people reach them.",
    },
    community: {
      label: "Community",
      title: "Being a father also means creating moments that matter.",
      body: "Cooking, parks, sports, computers, family events: simple opportunities to reconnect with your children and break isolation.",
      cta: "See community life",
      alts: [
        "A father and child cooking together",
        "A father and child in a Montréal park",
        "Community computer workshop",
      ],
    },
    org: {
      label: "Organisation",
      title: "REVERS CANADA",
      body: "RêvPÈRE is our community program for fathers. REVERS CANADA also develops other streams responding to essential needs.",
      streams: {
        housingLabel: "REVERS CANADA program",
        housingTitle: "Building stability too.",
        housingBody:
          "Housing remains the first condition of a lasting recovery. We are developing this stream with local partners.",
        housingCta: "Discover the housing stream",
        foodLabel: "REVERS CANADA program",
        foodTitle: "Concrete support when a family needs it.",
        foodBody:
          "Food security, emergency help and redistribution: direct support, without unnecessary steps.",
        foodCta: "Discover food support",
        intlLabel: "REVERS CANADA mission",
        intlTitle: "Our commitment can also cross borders.",
        intlBody:
          "Material donations: medication, clothing and supplies for communities and animals.",
        intlCta: "Discover the international stream",
      },
    },
    partners: {
      label: "Partners",
      title: "Complex problems are solved through networks.",
      body: "We are not trying to replace existing organisations. We want to be the entry point that leads to the right service, at the right time.",
      categories: [
        "Organisations",
        "Businesses",
        "Municipalities",
        "Foundations",
        "Trainers",
        "Employers",
      ],
      cta: "Build a partnership",
    },
    final: {
      title: "Every journey starts with a first step.",
      body: "Whether you are looking for work, want to become more independent with technology, or simply don't know where to start, RêvPÈRE can help you identify the next step.",
      ctaPrimary: "Start my journey",
      ctaSecondary: "Contact us",
    },
  },
} satisfies Record<"fr" | "en", unknown>;
